name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: koushik342
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  DOTNET_INSTALL_DIR: "/home/koushik/"

jobs:
  publish:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 'v4.0'
          
      - name: Build
        run: dotnet build ./helloworldapp.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./helloworldapp.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
